import React from 'react'

export default function Home() {
  return (
    <div>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste, in. Consequuntur quidem sit magni repellendus reprehenderit ad sunt, provident, eius iure quis assumenda recusandae deserunt laborum. Eos dolorum, nihil dolorem corporis fuga ea natus exercitationem ex veniam perferendis deserunt itaque, incidunt eaque cum odit sapiente deleniti possimus modi sit corrupti tempora quos delectus! Soluta explicabo ad excepturi adipisci, <i class="fa-brands fa-telegram"></i> fugiat voluptate veritatis nisi optio at enim? Placeat, corrupti inventore. Animi consequatur obcaecati sint optio dignissimos molestiae natus et repudiandae expedita unde enim in qui, id corrupti commodi facilis dicta maxime harum eveniet temporibus. Eveniet qui ipsam corporis, ea dicta id tenetur accusantium perferendis praesentium corrupti reiciendis, maiores asperiores ut atque, autem rerum? Voluptatum itaque ab est, totam placeat delectus? Corrupti facere sequi quas aperiam incidunt odit tempore placeat laborum magnam expedita vitae, quisquam reprehenderit cum eaque unde voluptates quaerat beatae maxime sint excepturi! Fugiat sapiente id ullam veritatis, nam itaque officiis possimus perferendis ut temporibus inventore et doloremque cupiditate consectetur! Nihil quam fuga doloremque incidunt nostrum! Aliquam, aut repellendus molestiae vero facilis nesciunt laborum possimus quos praesentium nobis doloremque corrupti quidem illum saepe cum autem assumenda. Culpa, veritatis ipsa provident facilis autem atque ducimus ut tempore voluptatem! Illo magni quis ea ab laboriosam corporis, doloremque fugit quae sint neque atque cupiditate error ipsum aliquid adipisci aut obcaecati placeat eius reprehenderit officia suscipit rem, totam minus? Et enim neque iste amet, possimus quia minima id eos corporis? Sunt error assumenda sint quos, ipsa sapiente mollitia eveniet accusantium quidem id atque unde consequatur molestiae cum, sed corporis deserunt odit excepturi quasi dolore omnis repellat? Quae, veritatis! Sed fugiat distinctio odit omnis. Alias, eos a? Ea omnis quis facere. Hic, quam? Quasi eveniet laudantium ut nihil dicta doloremque obcaecati saepe quia error iusto et ducimus, corrupti enim incidunt veritatis nostrum necessitatibus ratione blanditiis numquam.
    </div>
  )
}
